default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: stash-dev

test:
  <<: *default
  database: stash-test

production:
  <<: *default
  database: stash
